[module]
  [module.hugoVersion]
    min = '0.146.0'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[outputFormats]
  [outputFormats.llms]
    name= 'llms'
    baseName = 'llms'
    mediaType = 'text/plain'
    isPlainText = true
